### ISSUE TITLE
Crash log 5/6/2022

### ISSUE THREAD

**Issue by 1hazardousboi** [Bryan-Legend/dragon-forge#122] opened 2022-05-06 20:47 UTC
Mono path[0] = 'C:/Program Files (x86)/Steam/steamapps/common/Dragon Forge/Dragon Forge_Data/Managed'
Mono config path = 'C:/Program Files (x86)/Steam/steamapps/common/Dragon Forge/MonoBleedingEdge/etc'
Found 1 interfaces on host : 0) 10.1.10.60
Multi-casting "[IP] 10.1.10.60 [Port] 55294 [Flags] 2 [Guid] 3751552853 [EditorId] 1619836150 [Version] 1048832 [Id] WindowsPlayer(2,DESKTOP-WORK) [Debug] 1 [PackageName] WindowsPlayer [ProjectName] Dragon Forge" to [225.0.0.222:54997]...
Starting managed debugger on port 56853
Using monoOptions --debugger-agent=transport=dt_socket,embedding=1,server=y,suspend=n,address=0.0.0.0:56853
Initialize engine version: 2021.3.0f1 (6eacc8284459)
[Subsystems] Discovering subsystems at path C:/Program Files (x86)/Steam/steamapps/common/Dragon Forge/Dragon Forge_Data/UnitySubsystems
GfxDevice: creating device client; threaded=1; jobified=1
Direct3D:
    Version:  Direct3D 11.0 [level 11.0]
    Renderer: NVIDIA GeForce GTX 745 (ID=0x1382)
    Vendor:   NVIDIA
    VRAM:     4053 MB
    Driver:   30.0.15.1215
Begin MonoManager ReloadAssembly
- Completed reload, in  0.162 seconds
The referenced script on this Behaviour (Game Object '<null>') is missing!
<RI> Initializing input.

<RI> Input initialized.

<RI> Initialized touch support.

Couldn't create a Convex Mesh from source mesh "IrregularStoneE_LOD1" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Couldn't create a Convex Mesh from source mesh "IrregularStoneE_LOD0" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
Couldn't create a Convex Mesh from source mesh "Stonewall_1_LOD0" within the maximum polygons limit (256). The partial hull will be used. Consider simplifying your mesh.
UnloadTime: 0.795300 ms
Dragon Forge Version 1.0.8161.25640
Starting game mode The Curse
Loading save game Save Slot 1
Starting Quest The Curse
Starting Quest The Dragon Forge
Starting Quest Demon King
Look rotation viewing vector is zero
Look rotation viewing vector is zero
Look rotation viewing vector is zero
Look rotation viewing vector is zero
Look rotation viewing vector is zero
Look rotation viewing vector is zero
Look rotation viewing vector is zero
Look rotation viewing vector is zero
Look rotation viewing vector is zero
Reventador was defeated by Save Slot 1!
Complete Quest Demon King
Playing End Sequence
Saving to Dragon Forge - 1.sav
d3d11: failed to create staging 2D texture w=128 h=2 d3dfmt=10 [887a0005]

**Comment by Bryan-Legend** [comment] 2022-05-06 23:10
I'm going to assume this was fixed by driver update.

Forums say that it's typically caused by texture compression being on for NPOT sized textures. Or out of video memory.

**Closed by Bryan-Legend** 2022-05-06 23:10 UTC
